=== christophefondacci/pelmel-server/smaug/smaug-common/src/main/xsd/SearchReference.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.tvtrip.com/smaug/SearchReference"
	xmlns:tns="http://www.tvtrip.com/smaug/SearchReference"
	elementFormDefault="qualified">

	<element name="facetCategory">
		<complexType>
			<all>
				<element name="categoryCode" type="string" />
				<element name="groupingStrategy" type="string" />
				<element name="urlCode" type="string" />
				<element name="urlSeoTranslation" type="boolean" />
				<element name="range" default="false" type="boolean"
					minOccurs="0" maxOccurs="1" />
				<element ref="tns:scopes" minOccurs="0" maxOccurs="1" />
			</all>
			<attribute name="filterOnly" default="false" type="boolean" />
			<attribute name="facetCache" default="true" type="boolean" />
		</complexType>
	</element>

	<element name="sorter">
		<complexType>
			<all>
				<element name="fieldName" type="string" />
				<element name="ascending" type="boolean" default="true" />
				<element name="urlCode" type="string" />
				<element name="defaultIndex" type="int" minOccurs="0"
					maxOccurs="1" />
				<element name="sticky" type="boolean" default="false"
					minOccurs="0" maxOccurs="1" />
			</all>
		</complexType>
	</element>

	<element name="facetCategories">
		<complexType>
			<sequence>
				<element ref="tns:facetCategory" minOccurs="0" maxOccurs="unbounded" />
			</sequence>
		</complexType>
	</element>

	<element name="sorters">
		<complexType>
			<sequence>
				<element ref="tns:sorter" minOccurs="0" maxOccurs="unbounded" />
			</sequence>
		</complexType>
	</element>

	<element name="scopes">
		<complexType>
			<sequence>
				<element name="scope" type="string" minOccurs="0" maxOccurs="unbounded" />
			</sequence>
		</complexType>
	</element>
</schema>

=== christophefondacci/pelmel-server/smaug/smaug-common/src/main/resources/sorters.xml
<?xml version="1.0" encoding="UTF-8"?>
<sorters xmlns="http://www.tvtrip.com/smaug/SearchReference"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.tvtrip.com/smaug/SearchReference ../xsd/SearchReference.xsd ">

	<sorter>
		<fieldName>ranking</fieldName>
		<ascending>false</ascending>
		<urlCode>p</urlCode>
		<defaultIndex>1</defaultIndex>
	</sorter>

	<sorter>
		<fieldName>ranking</fieldName>
		<ascending>true</ascending>
		<urlCode>q</urlCode>
	</sorter>

	<!-- Sorting by price has been disabled until we have some prices to show -->
	<!-- <sorter> -->
	<!-- <fieldName>price</fieldName> -->
	<!-- <ascending>true</ascending> -->
	<!-- <urlCode>i</urlCode> -->
	<!-- </sorter> -->
	<!-- <sorter> -->
	<!-- <fieldName>price</fieldName> -->
	<!-- <ascending>false</ascending> -->
	<!-- <urlCode>j</urlCode> -->
	<!-- </sorter> -->

	<sorter>
		<fieldName>rating</fieldName>
		<ascending>false</ascending>
		<urlCode>a</urlCode>
	</sorter>

	<sorter>
		<fieldName>geo_distance</fieldName>
		<ascending>true</ascending>
		<urlCode>r</urlCode>
	</sorter>

	<sorter>
		<fieldName>name_sort</fieldName>
		<ascending>true</ascending>
		<urlCode>n</urlCode>
	</sorter>

	<sorter>
		<fieldName>name_sort</fieldName>
		<ascending>false</ascending>
		<urlCode>m</urlCode>
	</sorter>

	<sorter>
		<fieldName>has_video</fieldName>
		<ascending>false</ascending>
		<urlCode>v</urlCode>
		<defaultIndex>0</defaultIndex>
		<sticky>true</sticky>
	</sorter>
</sorters>

=== christophefondacci/pelmel-server/smaug/smaug-common/src/test/resources/facetCategoriesTest.xml
<?xml version="1.0" encoding="UTF-8"?>
<facetCategories xmlns="http://www.tvtrip.com/smaug/SearchReference"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://www.tvtrip.com/smaug/SearchReference ../xsd/SearchReference.xsd ">

        <facetCategory>
                <categoryCode>price</categoryCode>
                <groupingStrategy>OR</groupingStrategy>
                <urlCode>r</urlCode>
                <urlSeoTranslation>false</urlSeoTranslation>
                <range>true</range>
                <scopes>
                        <scope>LISTVIEW</scope>
                </scopes>
        </facetCategory>

        <facetCategory>
                <categoryCode>star</categoryCode>
                <groupingStrategy>OR</groupingStrategy>
                <urlCode>c</urlCode>
                <urlSeoTranslation>true</urlSeoTranslation>
                <scopes>
                        <scope>LISTVIEW</scope>
                </scopes>
        </facetCategory>

        <facetCategory>
                <categoryCode>amenity</categoryCode>
                <groupingStrategy>AND</groupingStrategy>
                <urlCode>a</urlCode>
                <urlSeoTranslation>true</urlSeoTranslation>
                <scopes>
                        <scope>LISTVIEW</scope>
                </scopes>
        </facetCategory>

<!-- 
        <facetCategory>
                <categoryCode>neighborhood</categoryCode>
                <groupingStrategy>OR</groupingStrategy>
                <urlCode>n</urlCode>
                <urlSeoTranslation>true</urlSeoTranslation>
        </facetCategory>
 -->

        <facetCategory>
                <categoryCode>brand</categoryCode>
                <groupingStrategy>OR</groupingStrategy>
                <urlCode>b</urlCode>
                <urlSeoTranslation>true</urlSeoTranslation>
                <scopes>
                        <scope>LISTVIEW</scope>
                </scopes>
        </facetCategory>

        <facetCategory>
                <categoryCode>style</categoryCode>
                <groupingStrategy>AND</groupingStrategy>
                <urlCode>y</urlCode>
                <urlSeoTranslation>true</urlSeoTranslation>
                <scopes>
                        <scope>LISTVIEW</scope>
                </scopes>
        </facetCategory>

        <facetCategory>
                <categoryCode>hotelName</categoryCode>
                <groupingStrategy>OR</groupingStrategy>
                <urlCode>m</urlCode>
                <urlSeoTranslation>false</urlSeoTranslation>
                <scopes>
                        <scope>LISTVIEW</scope>
                </scopes>
        </facetCategory>

        <facetCategory>
                <categoryCode>beginWith</categoryCode>
                <groupingStrategy>OR</groupingStrategy>
                <urlCode>w</urlCode>
                <urlSeoTranslation>false</urlSeoTranslation>
                <scopes>
                        <scope>CHILDREN</scope>
                        <scope>CITY</scope>
                        <scope>HOTEL</scope>
                        <scope>POI</scope>
                </scopes>
        </facetCategory>

        <facetCategory>
                <categoryCode>category</categoryCode>
                <groupingStrategy>OR</groupingStrategy>
                <urlCode>g</urlCode>
                <urlSeoTranslation>true</urlSeoTranslation>
                <scopes>
                        <scope>POI</scope>
                </scopes>
        </facetCategory>
</facetCategories>

=== christophefondacci/pelmel-server/smaug/smaug-common/src/test/resources/sortersTest.xml
<?xml version="1.0" encoding="UTF-8"?>
<sorters xmlns="http://www.tvtrip.com/smaug/SearchReference"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://www.tvtrip.com/smaug/SearchReference ../xsd/SearchReference.xsd ">

        <sorter>
                <fieldName>price</fieldName>
                <ascending>true</ascending>
                <urlCode>i</urlCode>
        </sorter>
        <sorter>
                <fieldName>price</fieldName>
                <ascending>false</ascending>
                <urlCode>j</urlCode>
        </sorter>
        <sorter>
                <fieldName>ranking</fieldName>
                <ascending>true</ascending>
                <urlCode>q</urlCode>
        </sorter>
        <sorter>
                <fieldName>ranking</fieldName>
                <ascending>false</ascending>
                <urlCode>p</urlCode>
        </sorter>
        <sorter>
                <fieldName>geo_distance</fieldName>
                <ascending>true</ascending>
                <urlCode>r</urlCode>
        </sorter>

        <sorter>
                <fieldName>name</fieldName>
                <ascending>true</ascending>
                <urlCode>n</urlCode>
        </sorter>
        <sorter>
                <fieldName>name</fieldName>
                <ascending>false</ascending>
                <urlCode>m</urlCode>
        </sorter>
        
        
</sorters>
